### ISSUE TITLE
pantalaimon does not encrypt the forwarded messages anymore(?)

### ISSUE THREAD

**Issue by BenWiederhake** [matrix-org/pantalaimon#102]
I have a client (matterbridge) that doesn't support Matrix' encryption, so I use pantalaimon as a good man in the middle that handles the encryption for me. (Awesome project btw!)

I am using version 0.10.1 (after running into #101). Now the forwarded messages are not encrypted anymore.

**To Reproduce**
1. Start pantalaimon (config see below)
2. Start matterbridge (which sends unencrypted messages, and I verified that it actually uses pantalaimon instead of connecting to matrix.org directly, because 1. I didn't upgrade matterbridge, it worked before, and so the behavior shouldn't have changed; and 2. if I kill pantalaimon then matterbridge complains about connection errors and messages don't arrive at matrix.org at all anymore.)
3. Cause a message to be sent through matterbridge→pantalaimon→matrix.org

**Expected behavior**
pantalaimon encrypts the message. Screenshot from last friday when it worked:

![Bildschirmfoto_2021-07-12_14-10-00](https://user-images.githubusercontent.com/2690845/125285510-03a99680-e31b-11eb-8f5d-d11f8f63916a.png)

(as shown by Element)

**Actual behavior**
pantalaimon does not encrypt the message, and instead seems to forward it raw. Screenshot from just now:

![Bildschirmfoto_2021-07-12_14-10-27](https://user-images.githubusercontent.com/2690845/125285657-2b006380-e31b-11eb-8fe3-027d4681b4a0.png)

(as shown by Element)

**Setup:**
 - OS: pantalaimon runs on Raspbian, I can access it via panctl.
 - Version:
        $ pantalaimon --version
        pantalaimon, version 0.10.1

(There isn't really a smartphone or a browser involved, so I don't know what I should supply here.)

pantalaimon.conf:
```
[Default]
LogLevel = Debug
SSL = True

[local-matrix]
Homeserver = https://matrix.org
ListenAddress = localhost
ListenPort = 20661
SSL = False
IgnoreVerification = False
UseKeyring = False
``

**Comment by begincalendar** [comment]
I'm experiencing this issue too and I didn't even realise until I noticed this ticket and checked my messages more closely.

This is disturbing that the encryption has just been disabled without any notice.

**Comment by poljar** [comment]
There are a couple of reasons why Pantalaimon might decide why it shouldn't encrypt for a room, after all it shouldn't encrypt if a room isn't marked as encrypted.

For example:

1. The room isn't considered to be in a joined state: https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L901
2. The room isn't considered to be encrypted: https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L921
3. The event type doesn't support encryption: https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L910

Number 3 doesn't seem to be relevant here.

Number 2 hinges on the fact that we receive a `m.room.encryption` state event, this event is stored and you're not able to downgrade the encryption in a room.

Number 1 of course is mutable so this might be the first thing to check out, the state of the room is fetched every time you restart Pantalaimon, so it might start working again after a restart.

As it is, I can't reproduce this while testing with Fractal, it might be some bridge specific issue.

**Comment by begincalendar** [comment]
I'm not using the same client as Ben (I'm using the Home Assistant Matrix integration), but I'm seeing execution flow to [here](https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L905) and can confirm that `client.rooms` is an empty dictionary.

**Comment by poljar** [comment]
Any idea which nio version is being used? I wonder if the client sync is failing for the same reason as https://github.com/matrix-org/pantalaimon/issues/101 and thus `client.rooms` stays empty forever.

**Comment by begincalendar** [comment]
How can I determine that (sorry I haven't published Python packages before)?
I see this in the "METADATA" file:
```
Requires-Dist: matrix-nio[e2e] (<0.18,>=0.14)
```

I'll try and debug whether the sync is failing in the meantime...

**Comment by poljar** [comment]
You can probably check that using pip 

```bash
pip list | grep nio
```

**Comment by begincalendar** [comment]
Of course, thanks.
```
matrix-nio             0.17.0
```

How can I check whether the sync requests are working?

I apologise for not working it out myself, but since I'm new to Matrix dev and you're obviously not, I figure it will be quicker to get to the bottom of this.

**Comment by poljar** [comment]
Right, the latest Pantalaimon allows `matrix-nio < 0.19.0` and [0.18.0](https://github.com/poljar/matrix-nio/blob/master/CHANGELOG.md#0180---2021-05-06) fixes an issue with the sync.

Upgrading things should fix this problem at least for you.

**Comment by begincalendar** [comment]
Thanks.
Upgraded to `pantalaimon            0.10.1` and still seeing the same issue.
I'm going to try nuking my `pan.db` (not before backing it up) and see if that helps.

**Comment by poljar** [comment]
Did you also upgrade `matrix-nio`?

**Comment by begincalendar** [comment]
I did not.
Upgrading `matrix-nio` appears to have done the trick
Thank you and my apologies for polluting this thread. I can delete my comments if necessary.

**Comment by poljar** [comment]
No need to delete them, chances are that OP is facing the same issue.

**Comment by begincalendar** [comment]
Given that pantalaimon's sole purpose revolves around E2EE, I'm still surprised that it falls back to no encryption.
I don't think this is a good default and I think it should at least be configurable to not send plaintext messages.

**Comment by poljar** [comment]
The problem lies in the fact that `matrix-nio` doesn't store the state, so we fetch it from the server every time you start Pantalaimon.

Usually it isn't a problem that a room isn't considered as `joined` anymore since that's clearly visible from the client as well, in this case the client and Pantalaimon ended up with different views of the state since the same bug that affected Pantalaimon in #101 affected `matrix-nio` and only one of them got upgraded.

The correct fix is to store the state, similarly how we store the fact that a room is encrypted (case number two), that way you can't at least downgrade the room to a non-joined one. Sadly I don't have the bandwidth to work on this right now but the long term plan is to utilize the [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/) in `matrix-nio` since the rust-sdk indeed has a state store.

**Comment by begincalendar** [comment]
Thanks for the technical insight.

I wasn't so much referring to the implementation reasons of why this is happening, I was referring to the end-user level functionality.
In my opinion, regardless of what the technical reason is that a message can't be forwarded with encryption, I would expect (at least via a configuration flag) that the message be dropped and maybe a warning emitted to `stderr` (or similar).
pantalaimon is built for E2EE, I'm less inclined to want to use it if it can silently not encrypt messages.

**Comment by poljar** [comment]
It's a bit more complicated than that since Pantalaimon shouldn't prevent a client from working in an unencrypted room either.

https://github.com/matrix-org/pantalaimon/pull/103 should prevent this particular failure mode to trigger a downgrade to unencrypted messages.

**Comment by begincalendar** [comment]
> It's a bit more complicated than that since Pantalaimon shouldn't prevent a client from working in an unencrypted room either.

That's fair enough, but I'm talking about if encryption is enabled and expected, there should never be a case where fallback to no encryption occurs.

**Comment by poljar** [comment]
As state, the problem is that we don't know if it's expected unless we sync the state with the server. I tweaked #103 a bit more so we don't forward requests to the server unless we know that we're joined.

As it is, the `/send` endpoint doesn't seem to allow events to be sent if we're not joined, only the `/state` endpoint seems to allow this for knocking.

**Comment by BenWiederhake** [comment]
Wow, this blew up! :D

> No need to delete them, chances are that OP is facing the same issue.

```
$ pip list | grep -Fi nio
matrix-nio     0.14.1
```

I was indeed, thank you! After `pip install matrix-nio==0.18` and restarting pantalaimon, it behaves correctly. Thanks, that fixes the issue in my case!

However, as @begincalendar already pointed out, the issue will crop up for other users as well. Maybe it might help to have stricter requirements on `matrix-nio` then? Maybe something like `Requires-Dist: matrix-nio[e2e] (<0.18,>=0.18)`?

**Comment by poljar** [comment]
> However, as @begincalendar already pointed out, the issue will crop up for other users as well. Maybe it might help to have stricter requirements on `matrix-nio` then? Maybe something like `Requires-Dist: matrix-nio[e2e] (<0.18,>=0.18)`?

Yeah, that's the plan. Once I merge #103 a release with a stricter nio version requirement will happen.

**Comment by poljar** [comment]
All done, if there's something else feel free to reopen.
